// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uinsure.Api.Persistence;

#nullable disable

namespace Uinsure.Api.Persistence.Migrations
{
    [DbContext(typeof(UinsureDbContext))]
    [Migration("20260927073455_AlignPropertyContract")]
    partial class AlignPropertyContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uinsure.Domain.Policies.Cancellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PolicyTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetainedPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<int>("UnusedDays")
                        .HasColumnType("int");

                    b.Property<int>("UsedDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTermId")
                        .IsUnique();

                    b.ToTable("Cancellations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cancellations_NonNegativeRefund", "[RefundAmount] >= 0");

                            t.HasCheckConstraint("CK_Cancellations_NonNegativeRetained", "[RetainedPremium] >= 0");
                        });
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PolicyTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTermId")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_PositiveAmount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("MutationRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.PolicyTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("HasClaims")
                        .HasColumnType("bit");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PredecessorPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PredecessorTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Premium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("PredecessorTermId")
                        .IsUnique()
                        .HasFilter("[PredecessorTermId] IS NOT NULL");

                    b.HasIndex("PredecessorTermId", "PredecessorPolicyId");

                    b.ToTable("PolicyTerms", null, t =>
                        {
                            t.HasCheckConstraint("CK_PolicyTerms_EndAfterStart", "[EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_PolicyTerms_PositivePremium", "[Premium] > 0");
                        });
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.PolicyholderSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PolicyTermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTermId");

                    b.ToTable("Policyholders", (string)null);
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.PropertySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PolicyTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTermId")
                        .IsUnique();

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CancellationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CancellationId")
                        .IsUnique();

                    b.HasIndex("PaymentId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Refunds", null, t =>
                        {
                            t.HasCheckConstraint("CK_Refunds_PositiveAmount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Cancellation", b =>
                {
                    b.HasOne("Uinsure.Domain.Policies.PolicyTerm", null)
                        .WithOne("Cancellation")
                        .HasForeignKey("Uinsure.Domain.Policies.Cancellation", "PolicyTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Payment", b =>
                {
                    b.HasOne("Uinsure.Domain.Policies.PolicyTerm", null)
                        .WithOne("Payment")
                        .HasForeignKey("Uinsure.Domain.Policies.Payment", "PolicyTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.PolicyTerm", b =>
                {
                    b.HasOne("Uinsure.Domain.Policies.Policy", null)
                        .WithMany("Terms")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uinsure.Domain.Policies.PolicyTerm", null)
                        .WithMany()
                        .HasForeignKey("PredecessorTermId", "PredecessorPolicyId")
                        .HasPrincipalKey("Id", "PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.PolicyholderSnapshot", b =>
                {
                    b.HasOne("Uinsure.Domain.Policies.PolicyTerm", null)
                        .WithMany("Policyholders")
                        .HasForeignKey("PolicyTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.PropertySnapshot", b =>
                {
                    b.HasOne("Uinsure.Domain.Policies.PolicyTerm", null)
                        .WithOne("Property")
                        .HasForeignKey("Uinsure.Domain.Policies.PropertySnapshot", "PolicyTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Refund", b =>
                {
                    b.HasOne("Uinsure.Domain.Policies.Cancellation", null)
                        .WithOne("Refund")
                        .HasForeignKey("Uinsure.Domain.Policies.Refund", "CancellationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uinsure.Domain.Policies.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Cancellation", b =>
                {
                    b.Navigation("Refund");
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.Policy", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("Uinsure.Domain.Policies.PolicyTerm", b =>
                {
                    b.Navigation("Cancellation");

                    b.Navigation("Payment");

                    b.Navigation("Policyholders");

                    b.Navigation("Property")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
